gestion/app/urls.py
from django.contrib import admin
from django.urls import path, include
from homepage.views import IndexView
from login.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
    path('', IndexView.as_view(), name='index'),
    path('login/', include('login.urls')),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/core/urls.py
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #path('fv/',myfirstview, name='first'),
    path('dashboard/', home, name='home'),
    path('category/listar/', CategoryListView.as_view(), name='listarCat'),
    path('category/crear/', CategoryCreateView.as_view(), name='crearCat'),
    path('category/editar/<int:pk>/', CategoryUpdateView.as_view(), name='editarCat'),
    path('category/eliminar/<int:pk>/', CategoryDeleteView.as_view(), name='eliminarCat'),
    #path('category/form/', CategoryFormView.as_view(), name='formCat'),
    #path('category/listar/', CategoryListView, name='listarCat'),
    #path('productos/listar/', ProductoListView.as_view(), name='listProd'),
    path('product/listar/', ProductListView.as_view(), name='listarPro'),
    path('product/crear/', ProductCreateView.as_view(), name='crearPro'),
    path('product/editar/<int:pk>/', ProductUpdateView.as_view(), name='editarPro'),
    path('product/eliminar/<int:pk>/', ProductDeleteView.as_view(), name='eliminarPro'),
]

gestion/core/models.py
from django.db import models
from datetime import datetime
from django.forms import model_to_dict
from django.conf import settings

# Create your models here.

class Type(models.Model):
    nombre= models.CharField(max_length=100, verbose_name='Nombre')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name='Tipo'
        verbose_name_plural='Tipos'
        ordering=['id']


class Category(models.Model):
    nombre= models.CharField(max_length=100, verbose_name='Nombre', unique=True)

    descripcion=models.TextField( max_length=500, verbose_name='Descripcion', null=True, blank=True)


    def __str__(self):
        return self.nombre

    def toJSON(self):
        item=model_to_dict(self)
        return item
    class Meta:
        verbose_name='Categoria'
        verbose_name_plural='Categorias'
        ordering=['id']

class Employer(models.Model):
    category=models.ManyToManyField(Category)
    type= models.ForeignKey(Type, on_delete=models.CASCADE)
    nombre= models.CharField(max_length=200, verbose_name='Nombres')
    dni= models.CharField(max_length=11, verbose_name='DNI', unique=True)
    fecha_registro= models.DateField(default=datetime.now , verbose_name='Fecha de Registro')
    fecha_creado=models.DateTimeField(auto_now=True)
    fecha_actualizacion=models.DateTimeField(auto_now_add=True)
    edad=models.PositiveIntegerField(default=0)
    salario=models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    estado=models.BooleanField(default=True)
    genero=models.CharField(max_length=1, default='M')
    avatar=models.ImageField(upload_to='avatar/%Y/%m/%d', null=True, blank=True)
    curriculum=models.FileField(upload_to='cv/%Y/%m/%d')

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name='Empleado'
        verbose_name_plural='Empleados'
        db_table = 'Empleados'
        ordering = ['id']

class Producto(models.Model):
    nombre=models.CharField(max_length=55)
    cat=models.ForeignKey(Category, on_delete=models.CASCADE)
    image=models.ImageField(upload_to='Productos', blank=True, null=True)
    pvp=models.DecimalField(default=0.0, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.nombre

    def get_image(self):
        if self.image:
            return '{}{}'.format(settings.MEDIA_URL, self.image)
        else:
            return '{}{}'.format(settings.STATIC_URL,'img/empty.png' )

gestion/core/forms.py
from django.forms import ModelForm,widgets,TextInput,Textarea
from .models import *

class CategoryForm(ModelForm):
    #def __init__(self,*args,**kwargs):
    #    super().__init__(*args,**kwargs)
    #    for form in self.visible_fields():
    #        form.fields.widgets.attrs['class']='form-control'
    
    class Meta:
        model=Category
        fields='__all__'

    def save(self, commit=True):
        data={}
        form=super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error']=form.errors
        except Exception as e:
            data['error']=str(e)
        return data

class ProductForm(ModelForm):
    #def __init__(self,*args,**kwargs):
    #    super().__init__(*args,**kwargs)
    #    for form in self.visible_fields():
    #        form.fields.widgets.attrs['class']='form-control'
    
    class Meta:
        model=Producto
        fields='__all__'

gestion/core/views.py
import random

from django.http import Http404, JsonResponse
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView
from django.core.paginator import Paginator
from .forms import *
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import *

# Create your views here.

def home(request):
    return render(request, 'core/home.html',{'title': 'Dashboard'})

class CategoryListView(ListView):
    model = Category
    template_name = 'core/category/list.html'

    #para devolver el queryset filtrado
 #   def get_queryset(self):
 #        return Category.objects.filter(nombre__startswith='D')
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request,*args,** kwargs)

    def post(self, request, *args, **kwargs):
        data={}
        try:
            action=request.POST['action']
            if action == 'searchdata':
                data=[]
                for i in Category.objects.all():
                    data.append(i.toJSON())
            else:
                data['error']="Ha ocurrido un error"
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data, safe=False)

 #modificando el diccionario que se le envia al template

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['title'] = "Listado de Categorias"
        #context['object_list'] = Producto.objects.all()
        context['create_url']=reverse_lazy('crearCat')
        context['list_url']=reverse_lazy('listarCat')
        return context

 #create view para crear registros de un model determinado

class CategoryCreateView(CreateView):
    model=Category
    form_class=CategoryForm
    template_name='core/category/create.html'
    success_url=reverse_lazy('listarCat')
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request,*args, **kwargs):
        data={}
        try:
            action=request.POST['action']
            if action=='add':
                form=CategoryForm(request.POST)
                #linea para llamar al save del formulario
                #data=form.save()
                #######Para hacer el AJAX desde el Post
                if form.is_valid():
                    form.save()
                else:
                    data['error']=form.errors
            else:
                data['error']="No entro ninguna opcion"
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

        self.object=None
        context=self.get_context_data(**kwargs)
        context['form']=form
        return render(request, self.template_name,context)

    def get_context_data(self,  **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Agregar Categoria"
        context['action']='add'
        context['list_url']=reverse_lazy('listarCat')
        
        #context['object_list'] = Producto.objects.all()
        return context 

class CategoryUpdateView(UpdateView):
    model=Category
    form_class=CategoryForm
    template_name='core/category/create.html'
    success_url=reverse_lazy('listarCat')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data={}
        try:
            action=request.POST['action']
            if action=='edit':
                form=self.get_form()
                data=form.save()
            else:
                data['error']="No ha ingresado ninguna opcion"
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['title']='Editar Categoria'
        context['list_url']=reverse_lazy('listarCat')
        context['action']='edit'
        return context

class CategoryDeleteView(DeleteView):
    model=Category
    template_name='core/category/delete.html'
    success_url=reverse_lazy('listarCat')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data={}
        try:
            self.object.delete()
        except Exception as e:
            data['error']=str(e)
        return HttpResponseRedirect(redirect_to='/core/category/listar/')
        #return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Eliminar Categoria"
        context['list_url']=reverse_lazy('listarCat')
        return context


class CategoryFormView(FormView):
    form_class = CategoryForm
    template_name ='core/category/create.html'
    success_url = reverse_lazy('listarCat')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request,*args, **kwargs)

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['title'] = 'form | Categoria'
        context['list_url']= reverse_lazy('listarCat')
        context['action']='add'
        return context


class ProductListView(ListView):
    model=Producto
    template_name='core/productos/list.html'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['title']="Listado de Productos"
        return context

class ProductCreateView(CreateView):
    model=Producto
    form_class=ProductForm
    template_name='core/productos/create.html'
    success_url=reverse_lazy('listarPro')
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    '''def post(self, request, *args, **kwargs):
        data={}
        try:
            print(request.POST)
            print(request.FILES)

        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)'''

    def get_context_data(self,  **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Agregar Producto"
        context['action']='add'
        context['list_url']=reverse_lazy('listarPro')
        
        #context['object_list'] = Producto.objects.all()
        return context

class ProductUpdateView(UpdateView):
    model=Producto
    form_class=ProductForm
    template_name='core/productos/create.html'
    success_url=reverse_lazy('listarPro')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        context['title']='Editar Producto'
        context['list_url']=reverse_lazy('listarPro')
        context['action']='edit'
        return context

class ProductDeleteView(DeleteView):
    model=Producto
    template_name='core/productos/delete.html'
    success_url=reverse_lazy('listarPro')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object=self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Eliminar Producto"
        context['list_url']=reverse_lazy('listarPro')
        return context

gestion/core/templates/core/category/create.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<form action="." method="post" id="send">
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                {% if action == 'add' %}
                <i class="bi bi-plus-circle "></i>
                {% else %}
                <i class="bi bi-pencil-square "></i>
                {% endif %}
                {{title}}
            </h3>
        </div>
        <div class="card-body ">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{action}}">
            {% if form.errors %}
            <div class=" alert alert-danger alert-dismissible">
                <button type="button" class=" close" data-dismiss="alert" aria-hidden="true">x</button>
                <h5><i class="icon bi bi-x-octagon"></i>Ha ocurrido un error al agregar el registro</h5>
                <ul>
                    {% for field in form %}
                    {% for error in field.errors %}
                    <li>{{error}}</li>
                    {% endfor %}
                    {% endfor %}

                </ul>
            </div>
            {% endif %}
            <div class=" form-group form-card text-center">
                <label for="id_nombre">Nombre: </label>
                <br>
                {{form.nombre}}
                <br><br><br>

                <label for="">Descripcion</label><br>
                {{form.descripcion}}
            </div> 
        </div>

    </div>
    <div class="  card-footer mt-3 px-5 mb-3">
        <button type="submit" class="  btn btn-primary btn-flat btnTest">
            <i class="bi bi-cassette"></i> Guardar Categoria
        </button>
        <a href="{% url 'listarCat' %}">
            <button type="button" class=" btn btn-danger">
                <i class="bi bi-x"></i> Cancelar
            </button>
        </a>
    </div>
    </div>
</form>


{% endblock %}

gestion/core/templates/core/category/delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<form action="." method="post" id="del">
    <div class="card card-default">
        <div class="card-header">
            <h3 class="card-title">
                <i class="bi bi-trash"></i>
                {{title}}
            </h3>
        </div>
        <div class="card-body ">
            {% csrf_token %}
            <input type="hidden" name="action" value="{{action}}">
            {% if form.errors %}
            <div class=" alert alert-danger alert-dismissible">
                <button type="button" class=" close" data-dismiss="alert" aria-hidden="true">x</button>
                <h5><i class="icon bi bi-x-octagon"></i>Ha ocurrido un error al agregar el registro</h5>
                <ul>
                    {% for field in form %}
                    {% for error in field.errors %}
                    <li>{{error}}</li>
                    {% endfor %}
                    {% endfor %}

                </ul>
            </div>
            {% endif %}

            <div class="alert alert-danger alert-dismissible">
                <h5><i class="icon fas fa-ban"></i> Notificacion!</h5>
                Estas seguro que quieres eliminar la categoria numero {{object.id}}
                </div>
        </div>

    </div>
    <div class="  card-footer mt-3 mb-3 px-5">
        <button type="submit" class="  btn btn-primary btn-flat btnTest">
            <i class="bi bi-cassette"></i> Si, aceptar
        </button>
        <a href="{{list_url}}" class="  btn btn-danger btn-flat">
            <i class="bi bi-cassette"></i> Cancelar
        </a>
    </div>
    </div>
</form>

{% endblock %}

gestion/core/templates/core/category/list.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
<div class="card card-default">
    <div class="card-header px-3 mb-3 mt-3 container">
    <h3 class="card-title">
    <i class="fas fa-exclamation-triangle bi bi-search"></i>
        {{title}}
    </h3>
    </div>  
    <div class="card card-body content-header mx-5 px-5">
<table id="example" class="display tab-content table-bordered table-responsive-md table-borderless justify-content-center" style="width:100%">
    <thead>
        <tr>
            <th scope="col" style="width: 10%;">Numero</th>
            <th scope="col" style="width: 20%;">Nombre</th>
            <th scope="col" style="width: 50%;">Descripcion</th>
            <th scope="col" style="width: 20%;">Opciones</th>
        </tr>
    </thead>
    <tbody>

    </tbody>
</table>
        </div>
    <div class="card-footer container">
    <a href="{{create_url}}"><button type="button" class="btn btn-primary btnTest" id="btnTest"><i class="bi bi-plus-circle"></i> Agregar Registro</button></a>
</div>

</div>

{% endblock %}